name: Move to In review

on:
  pull_request:
    types: [ready_for_review]

  workflow_dispatch:

jobs:
  move_to_review:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: GitHub Project Automation+
        uses: alex-page/github-project-automation-plus@v0.9.0
        with:
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
          project: Utilitas
          column: In review
